# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nomebase
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    image: dimitrimiranda/cakephp3.6:version1
    container_name: php7.2_web
    depends_on:
      - db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true

